version: '3'
services:
  mysql_db:
    image: mysql
    container_name: mysql_db_cinema
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'db_mysql_cinema'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_TCP_PORT: '3308'
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - '3308:3308'
    expose:
      - '3308'

volumes:
  mysql_data:

networks:
  default:
    name: mysqldb_network
